addEventListenerを使わずonClickでクリック処理を実装
zakino123/Rails-ActiveJob-App2 pull request #9
Opened 2022-03-17 05:53 UTC by zakino123

fix #8 

views/job_statuses/index.html.erbファイルにて、以下を追記。
・reload関数とcalljob関数を実装
・inputタグにonclick属性を追加し、クリック処理を実装

READMEに参考資料追記
その他、上記の変更に関連するルーティング及びコントローラーのメソッドのコメントを外した。

2022-03-17 07:06 UTC, JUNKI555 requested changes

2022-03-17 07:06 UTC, JUNKI555 commented on app/views/job_statuses/index.html.erb
> +  const calljob = () => {
関数式ではなく関数宣言で書くようにしてみてください
理由があって関数式を選択しているなら理由を教えてください

参考：
https://www.google.com/search?q=%E9%96%A2%E6%95%B0%E5%BC%8F+%E9%96%A2%E6%95%B0%E5%AE%A3%E8%A8%80+javascrip

https://qiita.com/nayuneko/items/e3ac089bdd6f6d726f9f

https://atmarkit.itmedia.co.jp/ait/articles/1605/18/news018.html#:~:text=%E9%96%A2%E6%95%B0%E5%AE%A3%E8%A8%80%E3%81%AF%E3%80%81%E5%AE%A3%E8%A8%80%E3%82%92,%E7%94%9F%E6%88%90%E3%81%95%E3%82%8C%E3%82%8B%E3%81%AE%E3%81%A0%E3%80%82

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/function

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/function

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions

2022-03-17 07:48 UTC, zakino123 commented on app/views/job_statuses/index.html.erb
> +  const calljob = () => {
アロー関数を書いていた理由としては以下になります。
①コードがより短くすることができる。
②関数宣言より新しい書き方で少し慣れておこうと考えました。
③呼び出す関数を一番最初の関数に固定する事ができるので、thisを使う時に分かりやすい。

今回は、①②の理由が大きいです。

記事を読んでいて、functionで関数宣言した方が無駄な処理が少ない事が理解できました。以下に関数宣言のメリットを記載致します。
・アロー関数だと、処理の際にfunction宣言をする為、処理の無駄。(コードが複雑になると、より負荷は大きい)
・省略するより、functionを書いた方が関数が宣言されていることが分かりやすい。

これ以外に関数宣言のメリットはあったりしますか。
何卒教えて頂けると嬉しいです。

2022-03-17 07:53 UTC, zakino123 reviewed
views/job_statuses/index.html.erbファイルにて、以下を変更。
reload関数とcalljob関数をアロー関数から関数宣言に変更。

2022-03-17 08:04 UTC, zakino123 reviewed
views/job_statuses/index.html.erbファイルにて、以下を変更。
reload関数とcalljob関数を関数式から関数宣言に変更。

2022-03-17 15:43 UTC, JUNKI555 commented on app/views/job_statuses/index.html.erb
> +  const calljob = () => {
> 呼び出す関数を一番最初の関数に固定する事ができるので、thisを使う時に分かりやすい。

まず、これが何を言っているのかよくわからないです。今回はthis使ってないですし。
関数式は関数宣言と違ってthisの巻き上げが行われないことを言っているのかな。。。

---

> アロー関数だと、処理の際にfunction宣言をする為、処理の無駄。(コードが複雑になると、より負荷は大きい)
> 省略するより、functionを書いた方が関数が宣言されていることが分かりやすい。
> 関数宣言は最初に生成され、関数の手前のコードで呼び出しがあってもエラーにならない。

それらがメリットという認識で十分です。

> アロー関数だと、処理の際にfunction宣言をする為

を少し僕の認識に合わせた表現をするならば

- 関数式は、実行フローが関数式に到達した時（呼び出した時）に解釈される
- 関数宣言は、コードブロックが実行される前に関数として解釈される

参考：

https://atmarkit.itmedia.co.jp/ait/articles/1605/18/news018.html#:~:text=%E9%96%A2%E6%95%B0%E5%AE%A3%E8%A8%80%E3%81%AF%E3%80%81%E5%AE%A3%E8%A8%80%E3%82%92,%E7%94%9F%E6%88%90%E3%81%95%E3%82%8C%E3%82%8B%E3%81%AE%E3%81%A0%E3%80%82

https://ja.javascript.info/function-expressions

です。
「**現在の** UKABUのコードにおいては」という前提ですが、
関数で行う処理が大きいものが多く、
「関数宣言は、コードブロックが実行される前に関数として解釈される」メリットを享受したいことが多いため
なるべく関数宣言を使うようにしています。

現在の、と強調したのは
今後 ReactなどのUIフレームワークを取り入れるなどしてアーキテクチャの前提が変わるのであれば
またその時に関数宣言を使うのか関数式を使うようにするのかは変わってくるためです。

2022-03-18 01:02 UTC, zakino123 commented on app/views/job_statuses/index.html.erb
> +  const calljob = () => {
> 関数式は関数宣言と違ってthisの巻き上げが行われないことを言っているのかな。。。
 
　はい。thisの巻き上げが行われない事です。今回は全く関係ないです。申し訳ありません。
　関数式のメリットを調べている際に出てきた情報を記述していました。

　参考：
　　https://qiita.com/10mi8o/items/2da84ab650f4caffdeea

> 「現在の UKABUのコードにおいては」という前提ですが、関数で行う処理が大きいものが多く、「関数宣言は、コードブロックが実行される前に関数として解釈される」メリットを享受したいことが多いためなるべく関数宣言を使う

　関数処理が大きく多い場合は、関数宣言のメリットを享受する事で、エラー対処を少なくし、開発スピードを上げることにも効果的な事を理解しました。

> 今後 ReactなどのUIフレームワークを取り入れるなどしてアーキテクチャの前提が変わるのであれば
またその時に関数宣言を使うのか関数式を使うようにするのかは変わってくる

　フロントのアーキテクチャの前提が変わる場合に、再度考慮する必要がある事も理解しました。

関数式と関数宣言の違いやメリットなど、調べたことがなかったので、貴重でした。
ありがとうございます！

2022-03-18 01:09 UTC, JUNKI555 approved these changes
![image](https://cdn-ak2.f.st-hatena.com/images/fotolife/c/chris4403/20010328/20010328171440.gif)

2022-03-18 01:10 UTC, merged